### ISSUE TITLE
Look into using gmusicproxy

### ISSUE THREAD

**Issue by askvictor** [squeezebox-googlemusic/squeezebox-googlemusic#11]
Using this might be a much cleaner way than using inline python

https://github.com/diraimondo/gmusicproxy

**Comment by gdhgdhgdh** [comment]
+1 for this. I have some experience of gmusicproxy - I wrote a little client-side app which used it for search, Vue.js for display  / track select, and submission of HTTP URLs to the current LMS playlist - a simple party playlist :)

https://bitbucket.org/gdhgdh/playlist-vue if anyone's bothered.

**Comment by davewongillies** [comment]
Some inspiration here https://github.com/Logitech/slimserver/issues/130#issuecomment-295231024

**Comment by davewongillies** [comment]
I'm going to close this issue. I think the right direction to take is to write a small helper that can be compiled and shipped with the plugin, like how the Spotty Spotify plugin has its [helper](https://github.com/michaelherger/spotty)
