### ISSUE TITLE
Slim::Player::Song::open (471) Warning: stream failed to open

### ISSUE THREAD

**Issue by flankendiskriminator** [squeezebox-googlemusic/squeezebox-googlemusic#14]
Hello,

I had the old plugin from Hechtus working for several months but now suddenly not anymore. Got the following error:

> Slim::Player::Song::open (471) Warning: stream failed to open

After some Debugging noticed that the Plugin gets an https://-Link from Google to Download the file but uses the Handler for an unencrypted HTTP-Session:

>Slim::Player::Protocols::**HTTP**::canDirectStream (267) [xx:xx:xx:xx:xx:xx] Not direct streaming because player is synced
>Slim::Player::Song::open (461) Opening stream (no direct streaming) using 
>Plugins::GoogleMusic::ProtocolHandler [googlemusic:track:xxxxx]
>Plugins::GoogleMusic::ProtocolHandler::new (36) Remote streaming Google Music track: **https**://r1---sn-4g5edn7l.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?xxxx
>Slim::Formats::RemoteStream::request (148) Response:
>Slim::Formats::RemoteStream::request (152) Warning: Invalid response code () from remote stream **https**://

Therefore i changed the ProtocolHandler.pm in line 5 from HTTP to HTTPS:

`use base qw(Slim::Player::Protocols::HTTP);`
to
`use base qw(Slim::Player::Protocols::HTTPS);`

Now it is working again as a charme :)

If you don't want use SSL for the transmission, you can also change the https:// in the URL to http:// automatically by adding the following line somewhere after line 33:

`#$streamUrl =~ s/https/http/g;`

But i prefer using HTTPS.

**Comment by kettenbach-it** [comment]
In my case, changing the URL to http and the ProtocolHandler to https does not work.
I have to either

- leave the ProtocolHandler to HTTP and ad `$streamUrl =~ s/https/http/g;`

OR

- change to ProtocolHandler to HTTP and leave `$streamUrl =~ s/https/http/g;` out or comment it out

Mixing protocol as proposed above doesn't work for me.

The code in the repo won't work as it is right now, because it does mix protocols.
You either have to switch to http and add `$streamUrl =~ s/https/http/g;` or change the protocol handler to HTTPS.

**Comment by flankendiskriminator** [comment]
> In my case, changing the URL to http and the ProtocolHandler to https does not work.

How should it? The problem is obviously that Google switch from http to https somewhere in the last weeks/months. So the only fixes are to either use https - what the change from the ProtocolHandler does - or force http - what the streamurl-change does.

I prefer using https, because it could be possible that Google blocks the http-request completly sometime in the future. But maybe there are people who would prefer using http.
