### ISSUE TITLE
No audio playback

### ISSUE THREAD

**Issue by nick295** [squeezebox-googlemusic/squeezebox-googlemusic#15]
I just setup max2play on my pi and got the Google music plugin running.  I can see all of my music but when I select to play one I don't get any audio. The album art shows like it's playing but it's not. I've seen threads about this kind of issue that are really old, but I'm new to this stuff and can't figure out what I need to do to correct it.  Any help would be appreciated.

**Comment by digiltd** [comment]
I had the same problem, applying the fix in #14 got it working again.

**Comment by nick295** [comment]
Thanks, but can you explain how to do that? I'm new to this and don't have a clue where to find the file.

**Comment by digiltd** [comment]
I don't know if mac2play installs things in the same locations as if you were installing them manually.

On my Pi where I installed LMS manually the location I found the `ProtocolHandler.pm` file is ` /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/`

You need to edit that file and change line 5 from:

`use base qw(Slim::Player::Protocols::HTTP);`

to

`use base qw(Slim::Player::Protocols::HTTPS);`

**Comment by mark-e-mark** [comment]
This was exactly the fix I needed. Thank you @digiltd.

**Comment by nick295** [comment]
Thank you, this work great

**Comment by digiltd** [comment]
Can you leave it open for the time being.... well, until the PR gets merged :)

**Comment by charettepa** [comment]
on Max2Play the folder mentioned above "/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/"
is found here instead
/usr/share/squeezeboxserver/Plugins/GoogleMusic/

changing to HTTPS corrected the issue as described

**Comment by askvictor** [comment]
I'm trying understand why this issue is happening to some people but not others - can everyone please tell me which Logitech Media Server/Squeezeboxserver version they are running, and whether changing HTTP->HTTPS has fixed the problem, or if it broke a previously working install?

**Comment by digiltd** [comment]
Logitech Media Server Version: 7.9.0 - 1487249278 @ Thu Feb 16 13:09:29 UTC 2017

Plugin version (though this was a bit of a surprise to me)  V7.1

https://github.com/Bucklew/squeezebox-googlemusic

I think i pulled in some bits of his version manually as he first discovered the https issue.

The repo for the plugin page is still the this one. If you want I can zip up the googlemusic plugin so you can do some diffing.

I have had no problems with it since the https issue.

I do have a device id from an android device (rather than faking one), not sure if that is a factor

**Comment by boogityman** [comment]
Hi everyone, I am experiencing a similar issue with a new install of Max2Play and the Google Music plugin. I found the file that @charettepa mentioned, but I have no idea how to open or edit this file within Max2Play. Is this even possible? I assume this is a really rube question, I am new to all of this so thank you in advance!

**Comment by charettepa** [comment]
You have to SSH to the system on port 22. You then edit the file using vi
or nano.  Make sure you nano or vi with su. Once in use keyboard arrows to
move around then press I to edit/insert, you can for our delete. Press ESC
to exit edit/insert mode then shift : .  Q to quit W! To write/save.

**Comment by boogityman** [comment]
Awesome that solved it for me!

**Comment by davein2it** [comment]
Fantastic no noise to beautiful music @digiltd @charettepa . Mucho Gracias

**Comment by tompdillon** [comment]
I had the same problem with LMS 7.9.1 and googlemusic from http://squeezebox-googlemusic.github.io/squeezebox-googlemusic/repository/repo.xml

Thanks for posts, I spent a good long day fighting this. Wish I had found this fix sooner.

**Comment by ultraschuppi** [comment]
fix #14 mentioned is still needed - but is also still working ;)

**Comment by davewongillies** [comment]
@ultraschuppi I've merged in my change from PR #25 and have also published a new version (0.7.0) which fixes the issue.

**Comment by davewongillies** [comment]
#25 has been merged, so I'm now closing this issue.
