### ISSUE TITLE
Python TypeError: can't concat bytes to str at line 112

### ISSUE THREAD

**Issue by BadgerPete** [squeezebox-googlemusic/squeezebox-googlemusic#23]
I am having issues getting the plugin to work on a FreeNas FreeBSD jail.  I have it running happily on multiple other servers running Centos 7 and Ubuntu.  Full (related) server log:

Plugins::GoogleMusic::Settings::handler (76) Not able to login to Google Play Music: TypeError: can't concat bytes to str at line 112

Python version: 2.7.13

Please note: my running instances have older versions of python albeit very minor difference: 2.7.12 on Ubuntu.

**Comment by lenzenmi** [comment]
I'm having the same issue with python 3.6.0.

**Comment by Riddlr** [comment]
You have to force recompile the inline python stuff with 2.7 - once you do that it should all work.

**Comment by davewongillies** [comment]
@Riddlr can you clarify what you mean by "force recompile"? Thanks.

**Comment by Riddlr** [comment]
It's been a while, but if I remember correctly, you have to check which version of python you are running - if it's not 2.7.xx (run python -V from the command line to see) you will have to modify your python symbolic link to point to the 2.7 path.  Once that is done you run python -V again it should say 2.7.xx.  

Then you need to recompile the cpan stuff

  sudo cpan App::cpanminus --force
  sudo cpanm --notest --force Inline
  sudo cpanm --notest --force Inline::Python
  sudo cpanm --notest --force IO::Socket::SSL

Again, this is just off the top of my head - could be some details I have missed

**Comment by davewongillies** [comment]
@Riddlr thanks. Given the error, it sounds like its the mostly likely cause. I'll close this issue. Feel free to re-open @BadgerPete if you're still having issues.
