### ISSUE TITLE
Slim::Web::JSONRPC::requestMethod (443) request not dispatchable!

### ISSUE THREAD

**Issue by askvictor** [squeezebox-googlemusic/squeezebox-googlemusic#28]
So my server (7.8.1) seems to have pulled in the updated plugin overnight. First up, the server hung and wasn't responsive, but seems to have started after a restart. So the good news is that the server and the plugin both seem to work. The bad news is that the log file is being flooded with 
`Slim::Web::JSONRPC::requestMethod (443) request not dispatchable!`
errors every 10 seconds, whether I'm playing something or not. The service is sitting on about 3% CPU usage pretty consistently; but I don't have a baseline to compare to.

So something isn't quite right on 7.8.1 still.

**Comment by davewongillies** [comment]
@askvictor I haven't pushed the updated plugin yet. I'd love to know what that log message is since I get it as well (even before having working gmusic plugin).

**Comment by askvictor** [comment]
heh; co-incidence then :)

**Comment by davewongillies** [comment]
@askvictor you aren't running home-assistant by any chance? I came across this issue https://github.com/home-assistant/home-assistant/issues/9305 which sounds familiar. I restarted my home-assistant instance and I'm no longer getting these messages

**Comment by askvictor** [comment]
Indeed I am; very interesting. I really should just disconnect squeezebox from HASS as I don't use the interface. Nice catch!
