### ISSUE TITLE
Remove SmartMix related code

### ISSUE THREAD

**Issue by michaelherger** [squeezebox-googlemusic/squeezebox-googlemusic#29]
SmartMix unfortunately has been dead for long. You can remove the relevant code from Plugin.pm and the modules which were loaded from there. And probably some code which was only used to cover that functionality.

https://github.com/squeezebox-googlemusic/squeezebox-googlemusic/blob/3d7698867ab3855026f76db689f22f641fe4a9f0/Plugin.pm#L130

https://github.com/squeezebox-googlemusic/squeezebox-googlemusic/blob/master/SmartMixAllAccess.pm

https://github.com/squeezebox-googlemusic/squeezebox-googlemusic/blob/master/SmartMixMyMusic.pm

**Comment by davewongillies** [comment]
Implemented in #30. Need to test it then I'll merge.

**Comment by davewongillies** [comment]
#30 is now merged.
