### ISSUE TITLE
Can repo.xml reference a https url to fetch the plugin zip file?

### ISSUE THREAD

**Issue by scelfo** [squeezebox-googlemusic/squeezebox-googlemusic#34]
https://github.com/squeezebox-googlemusic/squeezebox-googlemusic/blob/4f248002394d7c57861041ba2725f7b2a4b8a3ce/repository/repo.xml#L16

**Comment by davewongillies** [comment]
@scelfo yes it can. I'll fix this soon.

**Comment by davewongillies** [comment]
`repo.xml` now references [https](https://github.com/squeezebox-googlemusic/squeezebox-googlemusic/commit/6ec86fbaa2691b13f99e3d61182814aeec70f4a1#diff-057d601312c7caf8a05e228cd7469385R13) for the plugin
