### ISSUE TITLE
Having trouble installing

### ISSUE THREAD

**Issue by scelfo** [squeezebox-googlemusic/squeezebox-googlemusic#35]
I followed the installation instructions but when I enable the plugin, the squeezebox web ui says that it failed to load. Here are details from server.log. I'll be happy to try anything to get more information to debug this further, thanks!
```
[18-01-08 10:53:30.7610] Slim::bootstrap::tryModuleLoad (286) Warning: Module [Plugins::GoogleMusic::Plugin] failed to load: 
Error -- py_eval raised an exception at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Inline/Python.pm line 177.
BEGIN failed--compilation aborted at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/GoogleAPI.pm line 74.
Compilation failed in require at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Settings.pm line 20.
BEGIN failed--compilation aborted at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Settings.pm line 20.
Compilation failed in require at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Plugin.pm line 24. 
BEGIN failed--compilation aborted at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Plugin.pm line 24.
Compilation failed in require at (eval 869) line 1.
BEGIN failed--compilation aborted at (eval 869) line 1.

[18-01-08 10:53:30.7633] Slim::Utils::PluginManager::load (323) Error: Couldn't load Plugins::GoogleMusic::Plugin
```

**Comment by davewongillies** [comment]
@scelfo can you provide me the output from the following commands:
```
grep version /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/install.xml
which python
which pip
python --version
python -c 'import gmusicapi; print gmusicapi.__version__'
```

Also, what Linux distro are you running?

**Comment by scelfo** [comment]
I am running Ubuntu 16.04. The last command didn't work. Specifically:

Exception: Version mismatch: this is the 'cffi' package version 1.11.2, located in '/usr/local/lib/python2.7/dist-packages/cffi/api.pyc'.  When we import the top-level '_cffi_backend' extension module, we get version 1.5.2, located in '/usr/lib/python2.7/dist-packages/_cffi_backend.x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.

I am actually going to try installing a fresh installation of debian stable under vmware to use exclusively as a sandboxed squeezebox server. Once I saw that we needed to pin gmusicapi==10.1.2 in the installation instructions, I worried that I would have some conflicts with other things on my system. Beyond the conflicts, the sandbox just seems like a good idea all around.

If you have a suggestion for how to try fixing the error, I'd be happy to try it. Otherwise, I'll comment again if I can reproduce this in a clean sandbox.

Thanks!

**Comment by scelfo** [comment]
I got past this conflict by running:
```
$ apt-get remove --purge python-cffi-backend
```
Now in server.log I have a better error message, specifically:

```
base class package "Slim::Player::Protocols::HTTPS" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /var/lib/squeezeboxserver/cache/_Inline/lib /var/lib/squeezeboxserver/cache/InstalledPlugins /usr/share/squeezeboxserver/CPAN/arch/5.22/x86_64-linux-thread-multi /usr/share/squeezeboxserver/CPAN/arch/5.22/x86_64-linux-thread-multi/auto /usr/share/squeezeboxserver/CPAN/arch/5.22.1/x86_64-linux-gnu-thread-multi /usr/share/squeezeboxserver/CPAN/arch/5.22.1/x86_64-linux-gnu-thread-multi/auto /usr/share/squeezeboxserver/CPAN/arch/5.22/x86_64-linux-gnu-thread-multi /usr/share/squeezeboxserver/CPAN/arch/5.22/x86_64-linux-gnu-thread-multi/auto /usr/share/squeezeboxserver/CPAN/arch/x86_64-linux-gnu-thread-multi /usr/share/squeezeboxserver/CPAN/arch/5.22 /usr/share/squeezeboxserver/lib /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/sbin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .). 
 at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/ProtocolHandler.pm line 9.
BEGIN failed--compilation aborted at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/ProtocolHandler.pm line 9.
Compilation failed in require at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Plugin.pm line 26.
BEGIN failed--compilation aborted at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Plugin.pm line 26.
Compilation failed in require at (eval 825) line 1.
BEGIN failed--compilation aborted at (eval 825) line 1.

  ```

**Comment by scelfo** [comment]
Here are the answers to your earlier questions:
```
$ grep version /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/install.xml
<?xml version="1.0"?>
        <version>0.7.0</version>

$ which python
/usr/bin/python

$ which pip
/usr/local/bin/pip

$ python --version
Python 2.7.12

$ python -c 'import gmusicapi; print gmusicapi.__version__'
10.1.2
  ```

**Comment by davewongillies** [comment]
Oh and which version of logitechmediaserver do you have installed?
```
dpkg -l logitechmediaserver
```

**Comment by scelfo** [comment]
```$ dpkg -l logitechmediaserver
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  logitechmedias 7.9.0~146985 all          Streaming Audio Server```

**Comment by davewongillies** [comment]
I'd recommend updating to the latest 7.9.1 version:

http://www.mysqueezebox.com/update/?version=7.9.1&revision=1&geturl=1&os=debamd64

For my reference, where did you get that version of the logitechmediaserver package from?

**Comment by davewongillies** [comment]
And one other thing, you've got the `libio-socket-ssl-perl` package installed right?

**Comment by scelfo** [comment]
libio-socket-ssl-perl is installed. I'm not sure where I got 7.9.0, I'd assume I got it from the squeezebox download pages linked off www.mysqueezebox.com but now that I think about it, I don't think I've updated in a _long_ time.

**Comment by scelfo** [comment]
Now that I have updated to 7.9.1, the plugin installed without any issue and the server log is saying I'm not logged in--as expected. I'll go through the rest of the installation instructions!

**Comment by davewongillies** [comment]
:+1:

I'll have to update the instructions for this repo to suggest people upgrade to 7.9.1.

Your problem looks like it was due to somewhere within the various versions of logitechmediaserver 7.9.0, HTTPS support was added and some code I recently introduced incorrectly assumed that 7.9.0 always had HTTPS support.

**Comment by scelfo** [comment]
Makes sense! Related to my other issue that I opened today, does this mean on 7.9.1+ the xml file can specify a https url to download the Plugin zip?

**Comment by davewongillies** [comment]
@scelfo oh yeah, the xml file can specify https in the url. Its on my todo list.

**Comment by eliohann** [comment]
Got the same exact problem and can't find a solution.
LMS 7.9.2 on raspbian 9 on a pi 2

Here are the above version asked :
pi@rasp-lms ~ $ grep version /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/install.xml
<?xml version="1.0"?>
    <version>0.7.1</version>
pi@rasp-lms ~ $ which python
/usr/bin/python
pi@rasp-lms ~ $ which pip
/usr/bin/pip
pi@rasp-lms ~ $ sudo python -c 'import gmusicapi; print gmusicapi.__version__'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/__init__.py", line 4, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/webclient.py", line 6, in <module>
    from builtins import *  # noqa
ImportError: No module named builtins
pi@rasp-lms ~ $ dpkg -l logitechmediaserver
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom                      Version           Architecture      Description
+++-========================-=================-=================-=====================================================
ii  logitechmediaserver      7.9.2~1539967036  all               Streaming Audio Server
pi@rasp-lms ~ $

**Comment by jurgenweber** [comment]
@eliohann 
I am running this on FreeBSD and ports made my upgrade to 7.9.2 which also gave me the error found in the OP. I also found:

```
# perl -MIO::Socket::SSL -e "print \"Module installed.\\n\";"
Can't locate Net/SSLeay.pm in @INC (you may need to install the Net::SSLeay module) (@INC contains: /usr/local/lib/perl5/site_perl/mach/5.28 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.28/mach /usr/local/lib/perl5/5.28) at /usr/local/lib/perl5/site_perl/IO/Socket/SSL.pm line 19.
BEGIN failed--compilation aborted at /usr/local/lib/perl5/site_perl/IO/Socket/SSL.pm line 19.
Compilation failed in require.
BEGIN failed--compilation aborted.
```

So I installed
```
pkg install p5-Net-SSLeay
```
and now the module test for IO::Socket::SSL works:
```
# perl -MIO::Socket::SSL -e "print \"Module installed.\\n\";"
Module installed.
```

This also solved the 
```
Async::HTTP: Unable to load IO::Socket::SSL, will try connecting to SSL servers in non-SSL mode
``` 
error I was receiving (yes, p5-IO-Socket-SSL was already installed).

With this completed, the OP issue is now also resolved.
