### ISSUE TITLE
Use gmusicapi.Musicclient.oauth_login instead of password.

### ISSUE THREAD

**Issue by gpshead** [squeezebox-googlemusic/squeezebox-googlemusic#42]
Recent versions of the Python `gmusicapi` package have been updated to feature a `Musicclient.perform_oauth` one time setup function to store a music-access-only token for your account and a `Musicclient.oauth_login(Musicclient.FROM_MAC_ADDRESS)` call that easily replaces use of the old `login(username, password)` calls.

Modify `GoogleAPI.pm` and `Plugin.pm` to use these, getting rid of `GoogleAPI::get_device_id` and the device_id stuff from `Settings.pm` and it seems to work nicely for me.

**Comment by davewongillies** [comment]
@gpshead can you share what changes to the code you made to achieve this? Also, how does the oauth flow work?

**Comment by flankendiskriminator** [comment]
+1 :-)

The fixed password is always an alert in the security center.

**Comment by ultraschuppi** [comment]
@gpshead i hope that #45 is because i am still using username/pw-auth. would you mind sharing your modification so i can try this out?

i am not ready for switching to something else yet... ;)

**Comment by ultraschuppi** [comment]
quickfix:
* installed https://github.com/jeffmhubbard/gmusicproxy on my laptop
* ran `./GMusicProxy --oauth`
  * authorized
  * copypasted key
* scp generated file `~/.local/share/gmusicapi/mobileclient.cred` to LMS-machine to dir `/usr/share/squeezeboxserver/.local/share/gmusicapi`  
* replaced in `Plugin.pm`: 
```        
$googleapi->login($prefs->get('username'),
            decode_base64($prefs->get('password')),
                        $prefs->get('device_id'));
``` 
with 
`  $googleapi->oauth_login($prefs->get('device_id'));`

**Comment by ultraschuppi** [comment]
something like this should work for getting the access token (this is how https://github.com/jeffmhubbard/gmusicproxy is doing it internally as well)

```
~  python2    
Python 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gmusicapi import Mobileclient
>>> api = Mobileclient()
>>> api.perform_oauth();

Visit the following url:
 https://accounts.google.com/o/oauth2/v2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fskyjam&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=228293309116.apps.googleusercontent.com&access_type=offline
Follow the prompts, then paste the auth code here and hit enter: 
```

fetch URL, open it in plugin-settings to let the user authorize, copy paste the key in here, `mobileclient.cred` is then generated and persisted to disk through gmusicapi

**Comment by huubbouma** [comment]
I had the same issue so after some reading up on the perl syntax I made it work using the oauth login procedure. I also use a flask proxy to fix the songs from stopping to play before the song is finished so I'm not sure if this code will work for everybody out of the boxso your mileage may vary, but for me it seems to work fine. For now it's this code is in my fork but I can do a pull request after I clean up the proxy process.
See my fork here: https://github.com/huubbouma/squeezebox-googlemusic

**Comment by tmancill** [comment]
I did something similar to (but less comprehensive than) @huubbouma, as my fork depends on the oauth credentials file to be on the disk and uses gmusicproxy, since that's the proxy I've been using using to fix the interruption before the end of the song.  Only posting here in case it helps someone using GMusicProxy get up and running while we iron out the comprehensive pull-request.

- [squeezebox-googlemusic diff](https://github.com/squeezebox-googlemusic/squeezebox-googlemusic/compare/master...tmancill:oauth)
- [gmusicproxy diff](https://github.com/gmusicproxy/gmusicproxy/compare/master...tmancill:oauth)

I'll give flask and @huubbouma 's fork a try.

**Comment by nellistc** [comment]
hey @huubbouma, managed to get your plugin installed ok, but when trying to opening settings, it always fails with:

`Slim::Networking::IO::Select::__ANON__ (131) Error: Select task failed calling Slim::Web::HTTP::processHTTP: Can't call method "step1_get_authorize_url" on an undefined value at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Settings.pm line 125.
; fh=Slim::Web::HTTP::ClientConn=GLOB(0xf96d2e0)`

I am able to use oauth directly through python and get a token.

Any ideas? thanks!

**Comment by huubbouma** [comment]
Perhaps your gmusicapi version? Mine is 12.1.1

```
>>> import gmusicapi
>>> print(gmusicapi.__version__)

12.1.1
```

**Comment by nellistc** [comment]
I was on 12.1.0. Moved to 12.1.1, but same error occurs.

LMS is 7.9.1 - I'll try a newer release.

.. and, with the latest 7.9.2, still no good. Same message.

thanks

**Comment by shred** [comment]
>     * scp generated file `~/.local/share/gmusicapi/mobileclient.cred` to LMS-machine to dir `/usr/share/squeezeboxserver/.local/share/gmusicapi`

Just a small reminder to give proper permissions to the `mobileclient.cred` file on the LMS machine. On my CentOS installation, it's:

`chown -R squeezeboxserver: /usr/share/squeezeboxserver/.local/`

It took me a while to find out why I still couldn't log into Google music. :man_facepalming:

**Comment by nellistc** [comment]
Hi,

Got further thanks to that. Wasn't a permission problem, but the user running LMS didn't have the right version of gmusicapi installed. Fixed that and can now get to the settings screen, but I now get this:

`Slim::Networking::IO::Select::__ANON__ (131) Error: Select task failed calling Slim::Web::HTTP::processHTTP: FlowExchangeError: invalid_grantBad Request at line 133
; fh=Slim::Web::HTTP::ClientConn=GLOB(0xf630940)
`

when trying to save the settings with a valid device ID and token. Any idea?

**Comment by alexanderadam** [comment]
@huubbouma are you going to do a PR with your patches?

**Comment by huubbouma** [comment]
> @huubbouma are you going to do a PR with your patches?

Google is going to end the Google Music service soon. So I'm either going to switch to Spotify or YouTube Music but I don't think there's an API for the latter.
